---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM build manager
      command: npm run manager:build chdir={{homeDir}}/{{appDir}}
      register: npm_finished_build_manager

    - name: Running NPM build client
      command: npm run client:build chdir={{homeDir}}/{{appDir}}
      register: npm_finished_build_client
      when: npm_finished_build_manager.changed

    - name: Running NPM create symlink manager
      command: npm run manager:prod:create:symlink chdir={{homeDir}}/{{appDir}}
      when: npm_finished_build_manager.changed
