---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Create APP Directory
      file: path={{homeDir}}/{{appDir}} state=directory

    - name: Copy Private Key
      copy: src={{privateKey}} dest={{homeDir}} mode=0600

    - name: Git Clone Repo
      git: repo=git@gitlab.com:{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa
      register: git_finished

    - name: Create APP Directory files
      file: path={{homeDir}}/{{appDir}}/files state=directory
