---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM create symlink manager
      command: npm run manager:prod:create:symlink chdir={{homeDir}}/{{appDir}}
